CREATE OR REPLACE PROCEDURE QLTH.USER_LOGIN
    (USRNAME VARCHAR2, USR_ROLE NVARCHAR2, CNT OUT INTEGER)
AS
    LaSV NUMBER;
    LaNS NUMBER;
BEGIN
    CNT := 0;
    
    IF USR_ROLE = N'Sinh viên' THEN
        SELECT COUNT(*) INTO LaSV FROM QLTH.QLTH_SINHVIEN WHERE TO_CHAR(MASV) = USRNAME;
    ELSE    
        SELECT COUNT(*) INTO LaNS FROM QLTH.QLTH_NHANSU WHERE TO_CHAR(MANS) = USRNAME AND VAITRO = USR_ROLE;
    END IF;
    
    IF (LaNS = 1) THEN
        CNT := 1;
    END IF;
    
    IF (LaSV = 1) THEN
        CNT := 2;
    END IF;
END;
/

CREATE OR REPLACE PROCEDURE SYS.USP_RECOVER_TABLE
    (TAB_NAME IN VARCHAR2, RECOVER_TIME IN VARCHAR2, RES OUT NUMBER)
AS
    STRSQL VARCHAR2(2000);
BEGIN
    STRSQL := 'ALTER TABLE ' || TAB_NAME || ' ENABLE ROW MOVEMENT';
    EXECUTE IMMEDIATE (STRSQL);
    
    STRSQL := 'FLASHBACK TABLE ' || TAB_NAME || ' TO TIMESTAMP TO_TIMESTAMP(' || '''' || RECOVER_TIME || '''' || ', ''MM/DD/YYYY HH:MI:SS AM'')';
    EXECUTE IMMEDIATE (STRSQL);

    STRSQL := 'ALTER TABLE ' || TAB_NAME || ' DISABLE ROW MOVEMENT';
    EXECUTE IMMEDIATE (STRSQL);
    
    RES := 0;
END;
/