CREATE OR REPLACE PROCEDURE USER_LOGIN
    (USRNAME NUMBER, USR_ROLE NVARCHAR2, CNT OUT INTEGER)
AS
    
BEGIN
    CNT := 0;
    
    IF USR_ROLE = N'Sinh viên' THEN
        SELECT COUNT(*) INTO CNT FROM QLTH.QLTH_SINHVIEN WHERE MASV = USRNAME;
    ELSE    
        SELECT COUNT(*) INTO CNT FROM QLTH.QLTH_NHANSU WHERE MANS = USRNAME AND VAITRO = USR_ROLE;
    END IF;
END;
/

CREATE OR REPLACE VIEW UV_QLTH_DONVI_FORM
AS
SELECT DV.MADV, DV.TENDV, NS.HOTEN AS TDV FROM QLTH.QLTH_DONVI DV JOIN QLTH.QLTH_NHANSU NS ON dv.trgdv = NS.MANS;

GRANT select on UV_QLTH_DONVI_FORM TO RL_QLTH_NHANVIEN;

CREATE OR REPLACE VIEW UV_QLTH_KHMO_FORM
AS
SELECT kh.mahp, hp.tenhp, kh.hk, kh.nam, kh.mact, DV.TENDV
FROM QLTH.QLTH_KHMO KH JOIN QLTH.QLTH_HOCPHAN HP ON kh.mahp = hp.mahp
JOIN QLTH.QLTH_DONVI DV ON HP.MADV = DV.MADV;

grant select on UV_QLTH_KHMO_FORM TO RL_QLTH_NHANVIEN;