ALTER SESSION SET "_oracle_script"=true;
ALTER SESSION SET CONTAINER = XEPDB1;

--------------------------------------------------------------------------------
-- 1. TẠO CÁC USER CỦA DB QLTH VÀ CẤP CÁC ROLE TƯƠNG ỨNG CHO CÁC USER ĐÓ 
--------------------------------------------------------------------------------
-- TẠO PROCS
-- proc xóa user nhân sự
CREATE OR REPLACE PROCEDURE SYS.USP_DROPUSER_QLTH_NHANSU
AS
    CURSOR CUR IS (SELECT TO_CHAR(MANS)
                    FROM QLTH.QLTH_NHANSU
                    WHERE TO_CHAR(MANS) IN (SELECT USERNAME FROM ALL_USERS)
                    );
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(6);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(N2);
            
        STRSQL := 'DROP USER "'||N2||'" CASCADE';
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
-- proc xóa user sinh viên
CREATE OR REPLACE PROCEDURE SYS.USP_DROPUSER_QLTH_SINHVIEN
AS
    CURSOR CUR IS (SELECT TO_CHAR(MASV)
                    FROM QLTH.QLTH_SINHVIEN
                    WHERE TO_CHAR(MASV) IN (SELECT USERNAME FROM ALL_USERS)
                    );
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(8);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(N2);
            
        STRSQL := 'DROP USER "'||N2||'" CASCADE';
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
-- proc tạo user nhân sự
CREATE OR REPLACE PROCEDURE SYS.USP_CREATEUSER_QLTH_NHANSU
AS
    CURSOR CUR IS (SELECT TO_CHAR(MANS)
                    FROM QLTH.QLTH_NHANSU
                    WHERE TO_CHAR(MANS) NOT IN (SELECT USERNAME FROM ALL_USERS)
                    );
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(6);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(N2);
            
        STRSQL := 'CREATE USER "'||N2||'" IDENTIFIED BY "' || 123456 || '" CONTAINER = CURRENT';
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CONNECT, RESOURCE, RESTRICTED SESSION TO "'|| N2 || '"';
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
-- proc tạo user sinh viên
CREATE OR REPLACE PROCEDURE SYS.USP_CREATEUSER_QLTH_SINHVIEN
AS
    CURSOR CUR IS (SELECT TO_CHAR(MASV)
                    FROM QLTH.QLTH_SINHVIEN
                    WHERE TO_CHAR(MASV) NOT IN (SELECT USERNAME FROM ALL_USERS)
                    );
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(8);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(N2);
            
        STRSQL := 'CREATE USER "'||N2||'" IDENTIFIED BY "' || 123456 || '" CONTAINER = CURRENT';
        EXECUTE IMMEDIATE(STRSQL);
        STRSQL := 'GRANT CONNECT, RESOURCE, RESTRICTED SESSION TO "'|| N2 || '"';
        EXECUTE IMMEDIATE(STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
-- proc gán role sinh viên cho các user sinh viên
CREATE OR REPLACE PROCEDURE SYS.USP_GRANTROLE_QLTH_SINHVIEN
    (STRROLE VARCHAR2)
AS
    CURSOR CUR IS (SELECT TO_CHAR(MASV)
                    FROM QLTH.QLTH_SINHVIEN
                    WHERE TO_CHAR(MASV) IN (SELECT USERNAME
                                        FROM ALL_USERS));
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(8);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        
        STRSQL := 'GRANT "'||STRROLE||'" TO "'||N2||'"';
        EXECUTE IMMEDIATE (STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
-- proc gán các role tương ứng cho các user nhân sự
CREATE OR REPLACE PROCEDURE SYS.USP_GRANTROLE_QLTH_NHANSU
    (STRROLE VARCHAR2, LOAI NVARCHAR2)
AS
    CURSOR CUR IS (SELECT TO_CHAR(MANS)
                    FROM QLTH.QLTH_NHANSU
                    WHERE TO_CHAR(MANS) IN (SELECT USERNAME
                                        FROM ALL_USERS)
                    AND VAITRO = LOAI);
    STRSQL VARCHAR2(2000);
    N2 VARCHAR2(6);
BEGIN
    OPEN CUR;
    LOOP
        FETCH CUR INTO N2;
        EXIT WHEN CUR%NOTFOUND;
        
        STRSQL := 'GRANT "'||STRROLE||'" TO "'||N2||'"';
        EXECUTE IMMEDIATE (STRSQL);
    END LOOP;
    CLOSE CUR;
END;
/
-- THỰC THI PROCS
-- DROP USER
BEGIN 
    SYS.USP_DROPUSER_QLTH_SINHVIEN;
END;
/

BEGIN 
    SYS.USP_DROPUSER_QLTH_NHANSU;
END;
/
-- CREATE USER
BEGIN 
    SYS.USP_CREATEUSER_QLTH_NHANSU;
END;
/

BEGIN 
    SYS.USP_CREATEUSER_QLTH_SINHVIEN;
END;
/

BEGIN SYS.USP_GRANTROLE_QLTH_SINHVIEN('RL_QLTH_SINHVIEN'); END;
/

BEGIN SYS.USP_GRANTROLE_QLTH_NHANSU('RL_QLTH_NHANVIEN', N'Nhân viên cơ bản'); END;
/
BEGIN SYS.USP_GRANTROLE_QLTH_NHANSU('RL_QLTH_GIANGVIEN', N'Giảng viên'); END;
/
BEGIN SYS.USP_GRANTROLE_QLTH_NHANSU('RL_QLTH_GIAOVU', N'Giáo vụ'); END;
/
BEGIN SYS.USP_GRANTROLE_QLTH_NHANSU('RL_QLTH_TRUONGDV', N'Trưởng đơn vị'); END;
/
BEGIN SYS.USP_GRANTROLE_QLTH_NHANSU('RL_QLTH_TRUONGKHOA', N'Trưởng khoa'); END;
/