-- Chính sách bổ sung cho nhân viên
CREATE OR REPLACE VIEW QLTH.UV_QLTH_DONVI_FORM
AS
SELECT DV.MADV, DV.TENDV, NS.HOTEN AS TDV FROM QLTH.QLTH_DONVI DV JOIN QLTH.QLTH_NHANSU NS ON dv.trgdv = NS.MANS;

GRANT select on QLTH.UV_QLTH_DONVI_FORM TO RL_QLTH_NHANVIEN;

CREATE OR REPLACE VIEW QLTH.UV_QLTH_KHMO_FORM
AS
SELECT kh.mahp, hp.tenhp, kh.hk, kh.nam, kh.mact, DV.TENDV
FROM QLTH.QLTH_KHMO KH JOIN QLTH.QLTH_HOCPHAN HP ON kh.mahp = hp.mahp
JOIN QLTH.QLTH_DONVI DV ON HP.MADV = DV.MADV;

grant select on QLTH.UV_QLTH_KHMO_FORM TO RL_QLTH_NHANVIEN;

-- Chính sách bổ sung cho sinh viên:
-- Xem trên DONVI
GRANT SELECT ON QLTH.QLTH_DONVI TO RL_QLTH_SINHVIEN;
-- Xem kết quả học tập
CREATE OR REPLACE VIEW QLTH.UV_QLTH_KQHT_SV AS
    SELECT DK.NAM, DK.HK, DK.MAHP, HP.TENHP, HP.SOTC, DK.DIEMTHI, DK.DIEMQT, DK.DIEMCK, DK.DIEMTK
    FROM QLTH.QLTH_DANGKY DK JOIN QLTH.QLTH_HOCPHAN HP ON DK.MAHP = HP.MAHP;
    
GRANT SELECT ON QLTH.UV_QLTH_KQHT_SV TO RL_QLTH_SINHVIEN;