-- Chính sách bổ sung cho nhân viên
CREATE OR REPLACE VIEW QLTH.UV_QLTH_DONVI_FORM
AS
SELECT DV.MADV, DV.TENDV, NS.HOTEN AS TDV FROM QLTH.QLTH_DONVI DV JOIN QLTH.QLTH_NHANSU NS ON dv.trgdv = NS.MANS;

GRANT select on QLTH.UV_QLTH_DONVI_FORM TO RL_QLTH_NHANVIEN;

CREATE OR REPLACE VIEW QLTH.UV_QLTH_KHMO_FORM
AS
SELECT kh.mahp, hp.tenhp, kh.hk, kh.nam, kh.mact, DV.TENDV
FROM QLTH.QLTH_KHMO KH JOIN QLTH.QLTH_HOCPHAN HP ON kh.mahp = hp.mahp
JOIN QLTH.QLTH_DONVI DV ON HP.MADV = DV.MADV;

grant select on QLTH.UV_QLTH_KHMO_FORM TO RL_QLTH_NHANVIEN;

-- Chính sách bổ sung cho sinh viên:
-- Xem trên DONVI
GRANT SELECT ON QLTH.QLTH_DONVI TO RL_QLTH_SINHVIEN;
-- Xem kết quả học tập
CREATE OR REPLACE VIEW QLTH.UV_QLTH_KQHT_SV AS
    SELECT DK.NAM, DK.HK, DK.MAHP, HP.TENHP, HP.SOTC, DK.DIEMTHI, DK.DIEMQT, DK.DIEMCK, DK.DIEMTK
    FROM QLTH.QLTH_DANGKY DK JOIN QLTH.QLTH_HOCPHAN HP ON DK.MAHP = HP.MAHP;
    
GRANT SELECT ON QLTH.UV_QLTH_KQHT_SV TO RL_QLTH_SINHVIEN;
-- Xem thời gian đăng ký của chương trình mình
GRANT SELECT ON QLTH.QLTH_THOIGIANDK TO RL_QLTH_SINHVIEN;

CREATE OR REPLACE FUNCTION XEMTGDK_FUNC (P_SCHEMA IN VARCHAR2, P_OBJECT IN VARCHAR2)
    RETURN VARCHAR2
AS 
   LASV NUMBER;
   V_MACT VARCHAR2(5);
BEGIN 
    SELECT COUNT(*) INTO LASV FROM QLTH.QLTH_SINHVIEN WHERE TO_CHAR(MASV) = SYS_CONTEXT('USERENV', 'SESSION_USER');
    IF (LASV = 1) THEN
        SELECT MACT INTO V_MACT FROM QLTH.QLTH_SINHVIEN WHERE TO_CHAR(MASV) = SYS_CONTEXT('USERENV', 'SESSION_USER');
        RETURN 'MACT = ' || '''' || V_MACT || '''';
    ELSE 
        RETURN '';
    END IF;
END;
/

/*
BEGIN
    DBMS_RLS.DROP_POLICY(object_schema => 'QLTH',
    object_name => 'QLTH_THOIGIANDK',
    policy_name => 'XEM_KHMO_SV_POLICY');
END;
/
*/

BEGIN
    DBMS_RLS.ADD_POLICY(object_schema => 'QLTH',
    object_name => 'QLTH_THOIGIANDK',
    policy_name => 'XEMTGDK_POLICY',
    policy_function => 'XEMTGDK_FUNC',
    statement_types => 'SELECT' );
END;
/